'''
STREAMING:
1. stream agent process
2. stream llm tokens
3. stream reasoning tokens
4. stream custom updates
5. stream multiple modes

STREAM MODES:
    1. updates
    2. messages
    3. custom

1. AGENT PROGRESS: 
    * use stream or astream  with stream_mode = "updates"
    * This emits an event after every agent step.
2. LLM TOKENS:
    * To stream tokens as they are produced by the LLM, use stream_mode="messages"
3. CUSTOM UPDATES:
    * To stream updates from tools as they are executed, you can use get_stream_writer.
4. STREAM MULTIPLE MODES:
    * stream_mode=["updates", "custom"]

5. COMMON PATTERNS:
    a. stream these thinking / reasoning tokens as they’re generated by filtering standard content blocks for the type "reasoning"
    b. Streaming tool calls
    c. Streaming with human-in-the-loop
    d. Streaming from sub-agents
    e. 
'''